### ISSUE TITLE
Rust version in `Cargo.toml` is out of date

### ISSUE THREAD

**Issue by laurmaedje** [wasmi-labs/wasmi#1153]
When building with `1.77` as specified in `Cargo.toml`, you get this:
```
error[E0658]: associated type bounds are unstable
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmi-0.36.0/src/module/instantiate/mod.rs:54:40
   |
54 |         I: IntoIterator<Item = Extern, IntoIter: ExactSizeIterator>,
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information
```
Associated type bounds were stabilized in `1.79`.

**Comment by Robbepop** [comment]
@laurmaedje I just implemented a small CI job to guard against this.

Have you had to deal with this? https://github.com/wasmi-labs/wasmi/pull/1196
If so, how do you handle these (annoying) alerts?

**Comment by laurmaedje** [comment]
I personally find dependabot annoying in general, so I've disabled it completely.

Maybe you can trick it by using something like this:
```yaml
- uses: dtolnay/rust-toolchain@master
  with:
    toolchain: 1.79
```

Also confusing that it wants `1.90`... since that Rust version isn't out for a while.
