### ISSUE TITLE
Add negative tests for host integration

### ISSUE THREAD

**Issue by pepyakin** [wasmi-labs/wasmi#18]
For example, test what if:

- `ImportResolver` returned a signature that incompatible from requested,
- `Externals::invoke_index` returned a value when no value expected by the signature, and vice versa

**Comment by Robbepop** [comment]
This issue is no longer relevant since it is based on legacy `wasmi` that we no longer support. The current `wasmi` version has vastly differnt API with respect to the discussed topic.
