### ISSUE TITLE
Whether the behavior expected when pointer length out of bounds

### ISSUE THREAD

**Issue by luxinyi0105** [wasmi-labs/wasmi#757]
### TestCase
The given [testcase](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/09-08.zip) was simply mutated a wasm file, which was obtained by compiling C program generated with `Csmith` using `Emscripten Compiler`(Emcc). 

The original C program is `c_file.c`, the compilation results with Emscripten is `wasm_file.wasm`, and its wat format is `wat_file.wat`. 

We mutated the wat file to change its `i32.const 2` in line 20221 with `i32.const 3`. The result after mutation is `mutated_file.wat`, and its wasm format is `mutated_file.wasm`.

### Versions and Environment
Tools version: wasmi_cli 0.31.0
Operating system: Ubuntu 22.04.1
Architecture: x86_64

### Actual Results
```sh
$ ~/Software_new/wasmi/target/release/wasmi_cli mutated_file.wasm
executing File("mutated_file.wasm")::_start() ...
```
Output nothing.

### Expected Results
I use some other runtime tools, such as wasmer and wasmtime, to execute the same testcase. Wasmer outputs checksum results `checksum = 72658C22`, while wasmtime outputs runtime error due to pointer out of bounds. The execution results of these two tools are shown in the following figure.
![runtime result](https://github.com/paritytech/wasmi/assets/92167273/3bf43875-adb5-4780-80d5-520a8add95e2)

According to the issue I submitted in wasmtime: [bytecodealliance/wasmtime#6940](https://github.com/bytecodealliance/wasmtime/issues/6940), the length of the pointer, 952683808, is out of bounds. Wasmtime emits a `wasm traps` when handed an out-of-bounds pointer, while other runtime tools maybe return `ERRNO_FAULT`. 

Given that `wasmi simply uses the WASI implementation that is also used by wasmtime`. I wonder if the running result of wasmi for the given testcase is expected, or wasmi should also emit wasm traps like what wasmtime does. Thanks a lot!

**Comment by Robbepop** [comment]
The trapping behavior of Wasmtime is probably the correct one here. This issue should be triaged to see if this bug still exists with the WASI dependencies updated.

**Comment by Robbepop** [comment]
@luxinyi0105 I just re-ran the test case with Wasmi v0.38.0:

```shell
% time wasmi_cli 06-mutated.wat
Error: failed during execution of _start: Pointer out of bounds: Region { start: 816071770, len: 952683808 }
wasmi_cli 06-mutated.wat  0.01s user 0.00s system 91% cpu 0.020 total
```

So it seems to now also report the `pointer out of bounds` error from Wasmtime. However, funnily Wasmtime no longer reports a bug but instead happily outputs the checksum:

```shell
% time wasmtime 06-mutated.wat
checksum = 72658C22
wasmtime 06-mutated.wat  0.01s user 0.01s system 95% cpu 0.023 total
```

Maybe a regression in Wasmtime? 🤔
