### ISSUE TITLE
Incorrect behavior while meeting misaligned pointer

### ISSUE THREAD

**Issue by luxinyi0105** [wasmi-labs/wasmi#771]
### Describe the bug
While executing the given testcase with wasmi and other runtime tools, the results are different.

### Test Case
[The given testcase](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/09-25.zip) was simply mutated a wasm file, which was obtained by compiling C program generated with `Csmith` using `Emscripten Compiler`(Emcc). 

The original C program is `c_file.c`, the compilation results with Emscripten is `wasm_file.wasm`, and its wat format is `wat_file.wat`. 

We mutated the wat file to change its `i32.add` in line 11788 with `i32.sub`, and change all the `i32/i64.shl` with `i32/i64.xor`. The result after mutation is `mutated_file.wat`, and its wasm format is `mutated_file.wasm`.

### Actual Results
```sh
$ ~/Software_new/wasmi/target/release/wasmi_cli mutated_file.wasm
executing File("mutated_file.wasm")::_start() ...
checksum = CF2196F3
```

### Expected Results
I use some other runtime tools, such as wasmtime, to execute the same testcase. Its execution result is shown in the following figure.
![09-25](https://github.com/paritytech/wasmi/assets/92167273/20c8daa2-d185-40f8-9b8e-c0aea7d8c220)
From the result of wasmtime, we can see that the given testcase has problem about misaligned pointer, which triggers runtime error. 

Actually I have found several testcase which can trigger runtime error caused by `misaligned pointer` before submitting this issue. While using wasmi to execute those testcase, wasmi can sometimes trigger similar runtime errors, and more often it outputs nothing. The above two situations are explained in detail in Issue #743 .

In [wasmtime issue #7081](https://github.com/bytecodealliance/wasmtime/issues/7081), I have reported the different execution result while using different runtime tools to execute the same testcase.  The wasmtime developer believes that there is indeed a problem of `misaligned pointer`. So given the historical situation obtained from Wasmi executing such testcases(output nothing or get runtime error), it seems that wasmi has problems while executing the given testcase in this issue.

**Comment by Robbepop** [comment]
@luxinyi0105 I just re-ran this test case with Wasmi v0.38.0:

Wasmi v0.38.0:
```shell
% time wasmi_cli 05-mutated.wat  
checksum = CF2196F3
Error: failed during execution of _start: Pointer not aligned to 4: Region { start: 64803, len: 4 }
wasmi_cli 05-mutated.wat  0.01s user 0.01s system 64% cpu 0.030 total
```

Wasmtime:
```shell
% time wasmtime 05-mutated.wat
checksum = CF2196F3Error: failed to run main module `05-mutated.wat`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x7644 - <unknown>!<wasm function 41>
           1: 0x7bd0 - <unknown>!<wasm function 58>
           2: 0x870c - <unknown>!<wasm function 61>
           3: 0x7e70 - <unknown>!<wasm function 60>
           4: 0x7d09 - <unknown>!<wasm function 59>
           5: 0x8b39 - <unknown>!<wasm function 68>
           6: 0x7544 - <unknown>!<wasm function 40>
           7: 0x56a7 - <unknown>!<wasm function 12>
           8: 0x3f65 - <unknown>!<wasm function 7>
           9: 0x72d9 - <unknown>!<wasm function 34>
          10: 0x7253 - <unknown>!<wasm function 33>
    2: Pointer not aligned to 4: Region { start: 64803, len: 4 }
wasmtime 05-mutated.wat  0.05s user 0.02s system 204% cpu 0.034 total
```

Both tools now output the checksum and then report a trap.
So this bug seems to be resolved and the issue can be closed.
