### ISSUE TITLE
Maybe incorrect behavior while meeting misaligned pointer

### ISSUE THREAD

**Issue by luxinyi0105** [wasmi-labs/wasmi#772]
### Describe the bug
While executing the given testcase with wasmi and other runtime tools, the results are different.

### Test Case
[The given testcase](https://github.com/luxinyi0105/wasm_runtime_test/raw/main/09-26.zip) was simply mutated a wasm file, which was obtained by compiling C program generated with `Csmith` using `Emscripten Compiler`(Emcc). 

The original C program is `c_file.c`, the compilation results with Emscripten is `wasm_file.wasm`, and its wat format is `wat_file.wat`. 

We mutated the wat file to change its `i32.sub` in line 12189 with `i32.div_s`, and change all the `i32/i64.ge_u` with `i32/i64.le_s`. The result after mutation is `mutated_file.wat`, and its wasm format is `mutated_file.wasm`.

### Actual Results
```sh
$ ~/Software_new/wasmi/target/release/wasmi_cli mutated_file.wasm
executing File("mutated_file.wasm")::_start() ...
checksum = 
```

### Expected Results
I use some other runtime tools, such as wasmer, wasmtime, wasmedge and wasm-micro-runtime, to execute the same testcase. Wasmer and wasmtime outputs `checksum = ` with `runtime error` caused by `misaligned pointer`, while wasmedge and wasm-micro-runtime outputs `checksum = AF3BD5C3`. The execution results of different runtime tools are shown in the following figure.

![截图 2023-09-26 14-25-57](https://github.com/paritytech/wasmi/assets/92167273/e5962b95-bbba-4139-a7e3-c10a145d8c14) 

From the execution results, five different runtime tools obtained three different results while executing the same testcase. As I mentioned in issue #771, when wasmi encountered similar testcases before, it either output nothing or also output runtime errors caused by `misaligned pointers`. So I am not sure whether the behavior here is correct. Maybe this issue is the same as issue #771, and the detail still needs you to confirm. Thanks a lot!

**Comment by Robbepop** [comment]
@luxinyi0105 I just re-ran this test on Wasmi v0.38.0 and compared it to Wasmtime's output (which is presumably correct).

Wasmi:
```shell
% time wasmi_cli 03-mutated.wat
checksum = Error: failed during execution of _start: Pointer not aligned to 4: Region { start: 493, len: 4 }
wasmi_cli 03-mutated.wat  0.01s user 0.00s system 89% cpu 0.015 total
```

Wasmtime:
```shell
% time wasmtime 03-mutated.wat
checksum = Error: failed to run main module `03-mutated.wat`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x64b9 - <unknown>!<wasm function 23>
           1: 0x6a82 - <unknown>!<wasm function 40>
           2: 0x760b - <unknown>!<wasm function 43>
           3: 0x7597 - <unknown>!<wasm function 42>
           4: 0x6c08 - <unknown>!<wasm function 41>
           5: 0x7a38 - <unknown>!<wasm function 50>
           6: 0x6443 - <unknown>!<wasm function 22>
           7: 0x5ebf - <unknown>!<wasm function 12>
           8: 0x5949 - <unknown>!<wasm function 7>
           9: 0x61d8 - <unknown>!<wasm function 16>
          10: 0x6152 - <unknown>!<wasm function 15>
    2: Pointer not aligned to 4: Region { start: 493, len: 4 }
wasmtime 03-mutated.wat  0.05s user 0.02s system 194% cpu 0.034 total
```

Both tools now output the same error so I consider this bug fixed and close this issue.
