### ISSUE TITLE
Implement the Wasm `multi-memory` proposal

### ISSUE THREAD

**Issue by Robbepop** [wasmi-labs/wasmi#776]
This is about adding support for the [`multi-memory` Wasm proposal](https://github.com/WebAssembly/multi-memory).

The `multi-memory` Wasm proposal has been recently moved to Phase 4 and thus stabilization can be expected to happen soon.

Having `multi-memory` support in `wasmi` will be an enabler for certain use cases that try to emulate the component model as well as supporting other use cases.

**Comment by DavidAntliff** [comment]
Are there any working examples for this feature? I've had a hard time finding any docs other than a one-line remark on how to enable it in the `Config`...

If a host exports multiple memory regions, how does a guest, written in Rust, import these? At the moment, with a single region, I'm using linker flags to import the host-created region, and I imagine that multiple regions may need more elaborate linker flags?

Or, if a guest exports multiple memory regions, how does a host, written in Rust using Wasmi, get access to all of these regions? Does the API support the host obtaining handles to these guest-created regions?

**Comment by Robbepop** [comment]
@DavidAntliff would you be so kind an [open a discussion thread](https://github.com/wasmi-labs/wasmi/discussions) for this question so that other people can see this? I will then try to provide a proper answer to your question.

Tracking issues for Wasm proposal implementations are not the right place for these questions.

**Comment by DavidAntliff** [comment]
Sure: https://github.com/wasmi-labs/wasmi/issues/1773

I only asked here because it was the only thing I could find (apart from a blog entry) that mentions it.
